### ISSUE TITLE
Conflict between 'corepack' and 'pnpm env'.

### ISSUE THREAD

**Issue by akihironagai** [nodejs/corepack#236]
I installed Node and then installed pnpm with corepack. Then I ran 'pnpm env' and got an error.

```
# Commands
corepack enable
corepack prepare pnpm@latest --activate
pnpm env use --global 16
```

```
# Results
 ERR_INVALID_ARG_TYPE  The "path" argument must be of type string. Received undefined

pnpm [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:399:5)
    at validateString (node:internal/validators:163:11)
    at Object.resolve (node:path:1098:7)
    at getNodeExecPathInBinDir (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:71795:29)
    at envUse (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:108143:56)
    at async /root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217519:21
    at async main (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217488:34)
    at async runPnpm (/root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217718:5)
    at async /root/.cache/node/corepack/pnpm/7.27.0/dist/pnpm.cjs:217710:7
```

**Comment by aduh95** [comment]
Did you report this to pnpm?

**Comment by akihironagai** [comment]
> Did you report this to pnpm?

I just did.
