### ISSUE TITLE
I installed corepack with nodejs14.21.3,  

### ISSUE THREAD

**Issue by HuXinjing** [nodejs/corepack#285]
**I installed corepack with nodejs14.21.3,  two warnings showed up to me:**
npm WARN notsup Unsupported engine for corepack@0.19.0: wanted: {"node":">=16.20.0"} (current: {"node":"14.21.3","npm":"6.14.18"})
npm WARN notsup Not compatible with your version of node/npm: corepack@0.19.0

**By ignoring these warnings:**

(base) jason@jason-virtual-machine:~/Desktop$ corepack 
/home/jason/.volta/tools/image/packages/corepack/lib/node_modules/corepack/dist/lib/corepack.cjs:39787
      process.exitCode ??= code;
                       ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1029:16)
    at Module._compile (internal/modules/cjs/loader.js:1078:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/home/jason/.volta/tools/image/packages/corepack/lib/node_modules/corepack/dist/corepack.js:2:1)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)

**What's wrong with it? How could I install with nodejs14**

**Comment by aduh95** [comment]
> How could I install with nodejs14

You can't, Corepack only works on non-EOL Node.js versions (Node.js 14.x has reached EOL on 2023-04-30). I recommend you install Node.js 18.x or 20.x. You can also try to use an older version of Corepack, but understand that's not a supported use case.

**Comment by HuXinjing** [comment]
> > How could I install with nodejs14
> 
> You can't, Corepack only works on non-EOL Node.js versions (Node.js 14.x has reached EOL on 2023-04-30). I recommend you install Node.js 18.x or 20.x. You can also try to use an older version of Corepack, but understand that's not a supported use case.

Thx for ur reply. In https://github.com/RocketChat/Rocket.Chat, they give a flow of **Local-development** preparation, in **Install yarn** step, corepack is seemingly asked to install with nodejs14, I have no idea how could they make it, maybe they used a earlier version of nodejs14?

**Comment by merceyz** [comment]
Node.js v14.21.3 already includes Corepack so you shouldn't need to install it in this case.
