### ISSUE TITLE
`corepack install` fails if there is no `$HOME` directory

### ISSUE THREAD

**Issue by SimenB** [nodejs/corepack#329]
```Dockerfile
FROM ruby:2.7.8-alpine3.16

RUN apk update && \
  apk add --no-cache nodejs npm shadow && \
  rm -rf /var/cache/apk/*

RUN npm install -g corepack@0.20.x

RUN mkdir /hello

RUN useradd --uid 1000 user

RUN chown -R 1000 /hello

USER 1000

RUN corepack enable

WORKDIR /hello

RUN echo '{"packageManager": "yarn@1.22.20+sha256.f283c286f2731dc029203ff77bca71ce1a0db13174fe8cf61c9e9a917215ff02"}' > package.json

RUN corepack install
```

Gives the following error:

```
0.242 Adding yarn@1.22.20+sha256.f283c286f2731dc029203ff77bca71ce1a0db13174fe8cf61c9e9a917215ff02 to the cache...
0.253 Internal Error: EACCES: permission denied, mkdir '/home/user/.cache/node/corepack'
0.253     at mkdirSync (node:fs:1382:3)
0.253     at getTemporaryFolder (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:38948:27)
0.253     at installVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:39140:21)
0.253     at async Engine.ensurePackageManager (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:39350:32)
0.253     at async InstallLocalCommand.execute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:39833:5)
0.253     at async InstallLocalCommand.validateAndExecute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:37292:22)
0.253     at async Cli.run (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:38267:18)
0.253     at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:40228:12)
------
Dockerfile:23
--------------------
  21 |     RUN echo '{"packageManager": "yarn@1.22.20+sha256.f283c286f2731dc029203ff77bca71ce1a0db13174fe8cf61c9e9a917215ff02"}' > package.json
  22 |     
  23 | >>> RUN corepack install
  24 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c corepack install" did not complete successfully: exit code: 1
```

This diff fixes it

```diff
@@ -8,7 +8,7 @@ RUN npm install -g corepack@0.20.x
 
 RUN mkdir /hello
 
-RUN useradd --uid 1000 user
+RUN useradd --uid 1000 user --create-home
 
 RUN chown -R 1000 /hello
 ```

But it would be nice if `corepack` failed with a better error than `EACCES`. Probably just `Make sure your user has write access to $HOME` or some such.

**Comment by Medhansh404** [comment]
@aduh95 i hope this is all needed although in long we can add a fs.access() check early on to avoid this error, This may not be required entirely so i would like you to give me a head's up if needed i'll open a PR for that :)

**Comment by aduh95** [comment]
Fixed by https://github.com/nodejs/corepack/pull/343

**Comment by SimenB** [comment]
🎉
