### ISSUE TITLE
installation failure with Type Error: URL.canParse is not a function

### ISSUE THREAD

**Issue by ipmincubus1369** [nodejs/corepack#394]
Hi team, 
Did any of you get this error in 0.25.1? Currently reverted to 0.24.1 as a workaround.

```
yarn install --verbose
Type Error: URL.canParse is not a function
    at parseSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23613:21)
    at loadSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23690:11)
    at async findProjectSpec (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:23635:20)
    at async executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24209:18)
    at async BinaryCommand.validateAndExecute (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21164:22)
    at async _Cli.run (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22139:18)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:24265:12)
yarn install failed.
```

**Comment by styfle** [comment]
You're probably on an old version of Node.js

Some context is here: https://github.com/nodejs/corepack/pull/359#pullrequestreview-1881042380

**Comment by ipmincubus1369** [comment]
ah ok, we are indeed on older version - V16.
