### ISSUE TITLE
Corepack breaks when `integrity` key is missing from metadata, from artifactory

### ISSUE THREAD

**Issue by trc-mathieu** [nodejs/corepack#537]
Hi, I am actually using `artifactory` as npm proxy and it's missing the `dist/integrity` neither `dist/signatures` keys so this line breaks corepack since `integrity` is null. 

https://github.com/nodejs/corepack/blob/06e587218968c614371b187cc5b193a64273dbf4/sources/corepackUtils.ts#L294

I'm using `corepack@v0.29.2`

Would it be possible to fallback to `dist/shasum` in that case?

For instance, for corepack, I only have this
```
{
  "dist" : {
    "tarball" : "https://artifactory.<our domain>.com/artifactory/api/npm/npm/corepack/-/corepack-0.28.2.tgz",
    "shasum" : "2270c8fd1e4bebffda46ac0978d1f8b4202739ba"
  },
}
```
where npm has a lot more info

```
"dist": {
    "shasum": "2270c8fd1e4bebffda46ac0978d1f8b4202739ba",
    "tarball": "https://registry.npmjs.org/corepack/-/corepack-0.28.2.tgz",
    "fileCount": 54,
    "integrity": "sha512-YOo8PWW/SOQs7mqDIP6dDp9KoIyFvOJaoTofrXQEOIAZ5D24OpgKQ6JeW1HhXsRCMm1t1AunC/hXyqfT9G+5GQ==",
    "signatures": [
      {
        "sig": "MEQCIBBdptqO4kmk7aUSqWxmDQZ7O9acaxXdyHrFkM7P9jQPAiAINyseohZpq6pmY/Ufsw/XBgKcJy7buhcjDx5Icm9cjQ==",
        "keyid": "SHA256:jl3bwswu80PjjokCgh0o2w5c2U4LhQAE57gj9cz1kzA"
      }
    ],
    "unpackedSize": 1030119
  },
```
https://github.com/nodejs/corepack/blob/06e587218968c614371b187cc5b193a64273dbf4/sources/npmRegistryUtils.ts#L65

**Comment by aduh95** [comment]
What breaks Corepack? Can you be more specific? Like what command do you run and what error do you see?

**Comment by trc-mathieu** [comment]
So I basically do `export COREPACK_INTEGRITY_KEYS=0 && corepack enable && pnpm install`

Then I get this error because I don't have `integrity` from metadata from artifactory.
```
(node:35) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21626
  return `${version2}+sha512.${Buffer.from(integrity.slice(7), `base64`).toString(`hex`)}`;
                                                     ^
TypeError: Cannot read properties of undefined (reading 'slice')
    at fetchLatestStableVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21626:54)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async fetchLatestStableVersion2 (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:21738:14)
    at async Engine.getDefaultVersion (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22[34](https://gitlab.tower-research.com/SEFO/nuxt-webkit-starter/-/jobs/854611#L34)0:23)
    at async Engine.executePackageManagerRequest (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:22432:47)
    at async Object.runMain (/usr/local/lib/node_modules/corepack/dist/lib/corepack.cjs:231[36](https://gitlab.tower-research.com/SEFO/nuxt-webkit-starter/-/jobs/854611#L36):5)
Node.js v20.13.1
```
