### ISSUE TITLE
Unexpected identifier

### ISSUE THREAD

**Issue by IanVS** [nodejs/corepack#79]
I'm trying to clone and install dependencies in a project which appears to use corepack, and I'm having a difficult time.  I've tried to follow the directions, but am getting an error.  Here's what I've done.

```
▶ node --version
v16.13.0

▶ corepack enable

▶ corepack prepare yarn@3.0.2 --activate
Preparing yarn@3.0.2 for immediate activation...

▶ corepack yarn install
Syntax Error: Unexpected identifier
(function (exports, require, module, __filename, __dirname) { version https://git-lfs.github.com/spec/v1
                                                                      ^^^^^

SyntaxError: Unexpected identifier
    at new Script (node:vm:100:7)
    at NativeCompileCache._moduleCompile (/Users/ianvs/.nvm/versions/node/v16.13.0/lib/node_modules/corepack/dist/vcc.js:251:18)
    at Module._compile (/Users/ianvs/.nvm/versions/node/v16.13.0/lib/node_modules/corepack/dist/vcc.js:195:36)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (/Users/ianvs/.nvm/versions/node/v16.13.0/lib/node_modules/corepack/dist/vcc.js:170:20)
    at $K (/Users/ianvs/.node/corepack/yarn/3.0.2/yarn.js:242:4931)
    at ql (/Users/ianvs/.node/corepack/yarn/3.0.2/yarn.js:242:5785)
```

I guess this is an error coming from corepack?  I'm not really sure what's going on, to be honest.  Let me know if there is anything else I can do to help debug.  Thanks!

**Comment by IanVS** [comment]
Turns out the repo is using git lfs, which I've never worked with before.  Sorry for the noise.

**Comment by felixf4xu** [comment]
what are the additional steps to run `yarn install` for a git repo with lfs?
